== Environment Setup

Your environment has already been set up and you are ready to use your first ARO cluster.

== Connect to your bastion VM

. In the terminal window to the right connect to the bastion VM (you can also just click the command below to have it copied and executed automatically):
+
[TIP]
====
Answer `yes` when asked if to accept the host key.

The password for the user `azure` is `%bastion_password%`
====
+
[source,sh,role=execute]
----
%bastion_ssh_command%
----
+
.Click in the box below to copy and paste the string `yes` to your terminal:
+
[source,sh,role=execute]
----
yes
----
+
.Click in the box below to copy and paste the password to your terminal:
+
[source,sh,role=execute]
----
%bastion_password%
----

=== Validate installed tools

You will be using the `az` and `oc` command line tools throughout this lab.

. Verify that the `az` command line tool is installed:
+
[source,sh,role=execute]
----
az version
----
+
.Sample Output
[source,texinfo]
----
{
  "azure-cli": "2.49.0",
  "azure-cli-core": "2.49.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
----

. Validate the version of the OpenShift CLI:
+
[source,sh,role=execute]
----
oc version
----
+
.Sample Output
[source,texinfo]
----
Client Version: 4.11.26
Kustomize Version: v4.5.4
Server Version: 4.11.26
Kubernetes Version: v1.24.6+263df15
----

You are ready to start using your ARO cluster.
