== Access the OpenShift Console and CLI

=== Login to the OpenShift Web Console

. Make sure your cluster is ready
+
[source,sh,role=execute]
----
az aro show \
  --resource-group openenv-${GUID} \
  --name aro-cluster-${GUID} \
  --query "provisioningState" -o tsv
----
+
.Sample Output
[source,text,options=nowrap]
----
Succeeded
----

. First, let's configure your workshop environment with our helper variables.
To do so, let's run the following command:
+
[source,sh,role=execute]
----
cat << EOF >> ~/.workshoprc
export OCP_PASS=$(az aro list-credentials --name \
  aro-cluster-${GUID} --resource-group openenv-${GUID} \
  --query="kubeadminPassword" -o tsv)

export OCP_USER="kubeadmin"

export OCP_CONSOLE="$(az aro show --name aro-cluster-${GUID} \
  --resource-group openenv-${GUID} \
  -o tsv --query consoleProfile)"

export OCP_API="$(az aro show --name aro-cluster-${GUID} \
  --resource-group openenv-${GUID} \
  --query apiserverProfile.url -o tsv)"
EOF

source ~/.workshoprc

echo "source ~/.workshoprc" >>~/.bashrc

env | grep -E 'AZ_|OCP'
----
+
.Sample Output
[source,text,options=nowrap,subs="attributes"]
----
OCP_USER=kubeadmin
OCP_API={aro_api}
OCP_PASS={aro_kube_password}
OCP_CONSOLE={aro_console}
----
+
[INFO]
----
Helper Variables: We use helper variables extensively throughout this workshop, but we also include the commands we used to populate these helper variables to ensure you can craft these commands later.
----

. To access the OpenShift CLI tools (`oc`) and web console you will need to retrieve your cluster credentials.
The helper variables from above will make this simple!
+
To retrieve the credentials, run the following command:
+
[source,sh,role=execute]
----
az aro list-credentials --name aro-cluster-${GUID} --resource-group openenv-${GUID}
----
+
.Sample Output
[source,json,options=nowrap,subs="attributes"]
----
{
  "kubeadminPassword": "{aro_kube_password}",
  "kubeadminUsername": "kubeadmin"
}
----

. Next retrieve the console URL by running the following command:
+
[source,sh,role=execute]
----
az aro show --name aro-cluster-${GUID} --resource-group \
  openenv-${GUID} -o tsv --query consoleProfile
----
+
.Sample Output
[source,text,options=nowrap,subs="attributes"]
----
{aro_console}
----

. Finally, open the link to the console provided in a separate tab, and login with the provided credentials.

=== Login to the OpenShift CLI

Now that you're logged into the cluster's console, return to your Azure Cloud Shell.

. To login to the cluster using the OpenShift CLI tools (`oc`), first we need to retrieve the API server endpoint.
To do so, run the following command:
+
[source,sh,role=execute]
----
az aro show -g openenv-${GUID} -n aro-cluster-${GUID} --query apiserverProfile.url -o tsv
----
+
.Sample Output
[source,text,options=nowrap,subs="attributes"]
----
{aro_api}
----

. Now that we've captured the API server endpoint, we can login to the cluster by running the following command:
+
[source,sh,role=execute]
----
oc login "${OCP_API}" -u "${OCP_USER}" -p "${OCP_PASS}"
----
+
.Sample Output
[source,text,options=nowrap]
----
Login successful.

You have access to 70 projects, the list has been suppressed. You can list all projects with
'oc projects'

Using project "default".
----

Congratulations, you're now logged into the cluster and ready to move on to the workshop content.
