= Summit 2023: Building security-focused containerized applications with Azure Red Hat OpenShift

https://azure.microsoft.com/en-us/services/openshift/[Azure Red Hat OpenShift] is a fully managed Red Hat OpenShift service in Azure that is jointly engineered and supported by Microsoft and Red Hat.
In this lab, you'll go through a set of tasks that will help you understand some of the concepts of deploying and securing container based applications on top of Azure Red Hat OpenShift.

You can use this guide as an OpenShift tutorial and as study material to help you get started to learn OpenShift and integrating applications with Azure. The lab does touch on some basic Kubernetes concepts but does not go into detail explaining them as there is an expectation of a working knowledge of Kubernetes/OpenShift to do this lab.

.Some of the things you'll be going through:
* Use an ARO cluster to perform common tasks like:
  ** Experience self healing of applications
  ** Explore configuration management through configmaps, secrets and environment variables
  ** Explore networking within Kubernetes and applications
* Explore logging

Lastly, to tie it together in a real world scenario you will integrate the application with Azure Blob Storage and use KeyVault to store the connection secret. You will create an OpenShift secret that will pull the value from KeyVault and then the application will use that in order to read/write objects to Blob Storage.

You'll be doing the majority of the labs using the OpenShift CLI, but you can also accomplish them using the Azure Red Hat OpenShift web console as well.
