= Azure Red Hat OpenShift Workshop

https://azure.microsoft.com/en-us/services/openshift/[Azure Red Hat OpenShift] is a fully managed Red Hat OpenShift service in Azure that is jointly engineered and supported by Microsoft and Red Hat.

In this lab, you'll go through a set of tasks that will help you understand some of the concepts of deploying and securing container based applications on top of Azure Red Hat OpenShift.

You can use this guide as an OpenShift tutorial and as study material to help you get started to learn OpenShift.

== What to expect

During the workshop, we will take you through a series of content to help you learn how to deploy ARO, configure it, and securely deploy appplications to it using cloud based backing services such as Azure Container Registry and Azure Postgres.

During this hands on workshop we will cover the following:

- Deploying Azure Red Hat OpenShift clusters
- Perform Day 2 operations tasks such as configuring node and cluster scaling policies, configuring managed upgrades, and using labels for deterministic app placement on nodes
// - Learn how to leverage the built in Observability tooling
- Deploy an application to ARO, and then automate it using OpenShift GitOps and OpenShift Pipelines using modern tooling and practices.
- Make an application on OpenShift scalable and resistant to node failures and upgrades
- Deploy an application that uses an Azure Managed Database
- Learn how to use OpenShift Service Mesh for application observability and tracing
