:markup-in-source: verbatim,attributes,quotes

== Create an admin user for quick access

If you want to be able to access your cluster immediately through a cluster-admin user, you can follow these steps.
This is good if you need quick access to the cluster, which is great for this workshop.
Though the recommended approach is to use a formal identity provider to access the cluster (and then grant that user admin privileges, if desired).

. Run this command to create the admin user
+
[source,sh,role=execute]
----
rosa create admin --cluster=rosa-${GUID}
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Admin account has been added to cluster 'rosa-4fgbq'.
I: Please securely store this generated password. If you lose this password you can delete and recreate the cluster admin user.
I: To login, run the following command:

   oc login https://api.rosa-4fgbq.qrdf.p1.openshiftapps.com:6443 --username cluster-admin --password cD4xo-AnanH-DvB6L-6yndM

I: It may take several minutes for this access to become active.
----
+
[TIP]
====
Save the login command somewhere. Also take note of the password for your `cluster-admin` user.
====

. Copy the login command returned to you in the previous step and paste that into your terminal. This should log you into the cluster via the CLI so you can start using the cluster (answer `y` when promted if you want to accept the certificate).
+
[source,sh,role=copy]
----
oc login https://api.rosa-4fgbq.qrdf.p1.openshiftapps.com:6443 --username cluster-admin --password cD4xo-AnanH-DvB6L-6yndM
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 100 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
+
[TIP]
====
If you get an error that the *Login failed (401 Unauthorized)* wait a few seconds and then try again. It takes a few minutes for the cluster authentication operator to update itself after creating the cluster admin user.
====

. To check that you are logged in as the admin user you can run `oc whoami`:
+
[source,sh,role=execute]
----
oc whoami
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
cluster-admin
----

. You can also confirm by running the following command. Only a cluster-admin user can run this without errors.
+
[source,sh,role=execute]
----
oc get pod -n openshift-apiserver
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
NAME                        READY   STATUS    RESTARTS   AGE
apiserver-c5689956d-gp7hq   2/2     Running   0          17m
apiserver-c5689956d-nkf2w   2/2     Running   0          12m
apiserver-c5689956d-p9z7v   2/2     Running   0          16m
----

. You can now use the cluster as an admin user, which will suffice for this workshop. Though, for any other use, it is highly recommended to set up an IdP.
