== Configure Gitea

In later sections of this lab you will need to modify source code in a source code repository. While you could fork a repository into your own personal Github account for this lab you will just set up your own copy of Gitea - an open source repository.

Gitea is deployed by deploying an operator - you don't need to understand every command here - just make sure to finish all commands.

. Install the Gitea catalog source (this tells the OpenShift Operator Lifecycle Manager where to find the operator):
+
[source,sh,role=execute]
----
oc apply -f https://raw.githubusercontent.com/redhat-gpte-devopsautomation/gitea-operator/master/catalog_source.yaml
----
+
.Sample Output
[source,text,options=nowrap]
----
catalogsource.operators.coreos.com/redhat-gpte-gitea created
----

. Create a subscription to tell the OpenShift Operator Lifecycle Manager to install the operator:
+
[source,sh,role=execute]
----
cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitea-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitea-operator
  source: redhat-gpte-gitea
  sourceNamespace: openshift-marketplace
EOF
----
+
.Sample Output
[source,text,options=nowrap]
----
subscription.operators.coreos.com/gitea-operator created
----

. Wait until the Gitea operator pod is running (repeat this command every few seconds until the result matches the example):
+
[source,sh,role=execute]
----
oc get pod -n openshift-operators
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                                READY   STATUS    RESTARTS   AGE
gitea-operator-controller-manager-64fb9f9f7-m7k5h   2/2     Running   0          40s
----

. Create a project to deploy your Gitea instance:
+
[source,sh,role=execute]
----
oc adm new-project gitea
----
+
.Sample Output
[source,text,options=nowrap]
----
Created project gitea
----

. Finally deploy your copy of Gitea - this copy of Gitea will had an `admin` user and a `developer` user. The `developer` user will also have migrated repositories for you to use:
+
[source,sh,role=execute]
----
cat << EOF | oc apply -f -
---
apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: gitea
spec:
  giteaImageTag: 1.19.1
  giteaVolumeSize: 4Gi
  giteaSsl: true
  postgresqlVolumeSize: 4Gi
  giteaAdminUser: gitea-mgr
  giteaAdminPassword: "%generated_password%"
  giteaCreateUsers: true
  giteaGenerateUserFormat: developer
  giteaUserNumber: 1
  giteaUserPassword: "%generated_password%"
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/MicrosoftDocs/mslearn-aks-workshop-ratings-api.git
    name: ratings-api
    private: false
  - repo: https://github.com/MicrosoftDocs/mslearn-aks-workshop-ratings-web.git
    name: ratings-web
    private: false
EOF
----
+
.Sample Output
[source,text,options=nowrap]
----
gitea.gpte.opentlc.com/gitea created
----

You are now have a Gitea repository deployed and ready to use later on in this lab.
