== Connect to your ARO cluster

=== Command line

In order to log into your cluster you need credentials. If this is a brand new ARO cluster you can retrieve the `kubeadmin` credentials using the `az` command line tool:

. Get the `kubeadmin` credentials:
+
[source,sh,role=execute]
----
az aro list-credentials \
  --name aro-cluster-%guid% \
  --resource-group openenv-%guid%
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
{
  "kubeadminPassword": "%aro_kube_password%",
  "kubeadminUsername": "kubeadmin"
}
----

. Log into your OpenShift cluster (note the values have already been filled in):
+
[source,sh,role=execute]
----
oc login -u kubeadmin -p %aro_kube_password% --insecure-skip-tls-verify=true %aro_api%
----
+
.Sample Output
[source,text,options=nowrap]
----
Login successful.

You have access to 68 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----

== Log into the Web Console

. Retrieve the web console URL from Azure:
+
[source,sh,role=execute]
----
az aro list -o json | jq -r '[.[]|select(.name=="aro-cluster-%guid%")][0].consoleProfile.url'
----
+
.Sample Output
[source,text,options=nowrap]
----
%aro_console%
----

. Open another browser window and use the URL you just retrieved to navigate to the Azure Red Hat OpenShift Web Console.

. Click on `kube:admin` to select the identity provider.

. Use the following credentials to log into the web console:
* User: `kubeadmin`
* Password: `%aro_kube_password%`

. Feel free to explore the web console.
