:preconfigure_aad: %preconfigure_aad%
ifndef::preconfigure_aad[]
:preconfigure_aad: false
endif::[]
= Azure AD for Cluster Authentication

preconfigure_aad: {preconfigure_aad}

Authentication to your cluster is best managed via Azure Active Directory.

ifeval::[{preconfigure_aad} == true]
Your ARO cluster has been preconfigured with Azure AD. Please complete the link:./1b-explore-aad[Explore Azure Active Directory for Cluster Authentication] module.
endif::[]
ifeval::[{preconfigure_aad} == false]
Your ARO cluster has NOT been preconfigured with Azure AD. Please complete the link:./1a-configure-aad[Configure Azure Active Directory for Cluster Authentication] module.
endif::[]

ifeval::["{preconfigure_aad}" == ""]
ifeval::[{preconfigure_aad} == true]
Your ARO cluster has been preconfigured with Azure AD. Please complete the link:./1b-explore-aad[Explore Azure Active Directory for Cluster Authentication] module.
endif::[]
ifeval::[{preconfigure_aad} == false]
Your ARO cluster has NOT been preconfigured with Azure AD. Please complete the link:./1a-configure-aad[Configure Azure Active Directory for Cluster Authentication] module.
endif::[]

ifeval::["{preconfigure_aad}" == ""]
Depending on which environment your instructor deployed this authentication is either preconfigured or you need to set it up.

Your instructor should tell you how your environment was set up.

You will need to do *one* of the following two modules:

* link:./1a-configure-aad[Configure Azure Active Directory for Cluster Authentication]
* link:./1b-explore-aad[Explore Azure Active Directory for Cluster Authentication]
endif::[]

