=== Create and configure a project for the service mesh

Now, let's proceed with deploying a workload to test our service mesh.

. First, let's create a project (namespace) for us to deploy our workload into.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc new-project bookinfo
----
+
.Sample Output
[source,text,options=nowrap]
----
Now using project "bookinfo" on server "https://api.rosa-6n4s8.1c1c.p1.openshiftapps.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname
----

. Next, let's label that project (namespace) to enable the service mesh injection for all applications in the project.
+
[source,sh,role=execute]
----
oc label namespace bookinfo istio-injection=enabled
----
+
.Sample Output
[source,text,options=nowrap]
----
namespace/bookinfo labeled
----

. Even though we've enabled service mesh injection in the project, we also need to add our project (namespace) to the `ServiceMeshMemberRoll`, which limits the scope of the service mesh control plane to only projects in the member roll.
To add the project to the `ServiceMeshMemberRoll`, run the following command:
+
[source,sh,role=execute]
----
cat << EOF | oc apply -f -
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - bookinfo
EOF
----
+
.Sample Output
[source,text,options=nowrap]
----
servicemeshmemberroll.maistra.io/default created
----

. Next, let's verify the `ServiceMeshMemberRoll` was created successfully.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc -n istio-system get smmr -o wide
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME      READY   STATUS       AGE   MEMBERS
default   1/1     Configured   20s   ["bookinfo"]
----
+
The service mesh member roll was successfully configured when the STATUS column is `Configured` and your project shows up in the MEMBERS column.

=== Deploy our test workload

. Now that we've configured the service mesh for our project, let's deploy our bookinfo workload into our project.
To do so, run the following command to create the necessary resources:
+
[source,sh,role=execute]
----
oc -n bookinfo apply -f \
  https://raw.githubusercontent.com/rh-mobb/rosa-workshop-content/main/rosa-content/assets/scripts/bookinfo.yaml
----
+
.Sample Output
[source,text,options=nowrap]
----
service/details created
serviceaccount/bookinfo-details created
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "details" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "details" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "details" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "details" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/details-v1 created
service/ratings created
serviceaccount/bookinfo-ratings created
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "ratings" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "ratings" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "ratings" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "ratings" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/ratings-v1 created
service/reviews created
serviceaccount/bookinfo-reviews created
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "reviews" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "reviews" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "reviews" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "reviews" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/reviews-v1 created
deployment.apps/reviews-v2 created
deployment.apps/reviews-v3 created
service/productpage created
serviceaccount/bookinfo-productpage created
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "productpage" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "productpage" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "productpage" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "productpage" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/productpage-v1 created
----
+
You may ignore the Warnings.
+
Interested in seeing the configuration you're deploying?
Check it out on GitHub https://github.com/rh-mobb/rosa-workshop-content/blob/main/rosa-content/assets/scripts/bookinfo.yaml[here].

. Now, let's create the service mesh ingress gateway.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc -n bookinfo apply -f \
  https://raw.githubusercontent.com/rh-mobb/rosa-workshop-content/main/rosa-content/assets/scripts/bookinfo-gateway.yaml
----
+
.Sample Output
[source,text,options=nowrap]
----
gateway.networking.istio.io/bookinfo-gateway created
virtualservice.networking.istio.io/bookinfo created
----

=== Adding default destination rules

. Next, let's add some destination rules.
Destination rules define policies that apply to traffic intended for a service after routing has occurred.
To create the rules, run the following command:
+
[source,sh,role=execute]
----
oc -n bookinfo apply -f \
  https://raw.githubusercontent.com/rh-mobb/rosa-workshop-content/main/rosa-content/assets/scripts/destination-rule-all.yaml
----
+
.Sample Output
[source,text,options=nowrap]
----
destinationrule.networking.istio.io/productpage created
destinationrule.networking.istio.io/reviews created
destinationrule.networking.istio.io/ratings created
destinationrule.networking.istio.io/details created
----

=== Verifying the Bookinfo installation

. First, let's verify that all pods are running and ready by running the following command:
+
[source,sh,role=execute]
----
oc -n bookinfo get pods
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-7d55897577-gvwm5       2/2     Running   0          98s
productpage-v1-8648b7c9b5-txfvk   2/2     Running   0          96s
ratings-v1-84599899df-twc8g       2/2     Running   0          97s
reviews-v1-59647cf6c-pbrn8        2/2     Running   0          97s
reviews-v2-5fc469b4ff-fp4fn       2/2     Running   0          97s
reviews-v3-7d84688cc9-kktpt       2/2     Running   0          97s
----

. Next, let's get the URL for the product page.
To do so, run the following command:
+
[source,sh,role=execute]
----
echo "http://$(oc -n istio-system get route istio-ingressgateway -o jsonpath='{.spec.host}')/productpage"
----
+
.Sample Output
[source,text,options=nowrap]
----
http://istio-ingressgateway-istio-system.apps.rosa-6n4s8.1c1c.p1.openshiftapps.com/productpage
----

. Copy and paste the URL provided in the previous step into your web browser and verify the Bookinfo product page is successfully deployed.
+
You should see a book review of "The Comedy of Errors".

== Summary 

Here you learned how to:

* Enroll a project into a Service Mesh
* Configure default destination rules
* Access an application via the Service Mesh Ingress Gateway
