== Weighted Routing

Requests are routed to services within a service mesh with virtual services.
Each virtual service consists of a set of routing rules that are evaluated in order.
Red Hat OpenShift Service Mesh matches each given request to the virtual service to a specific real destination within the mesh.

Without virtual services, Red Hat OpenShift Service Mesh distributes traffic using round-robin load balancing between all service instances.
With a virtual service, you can specify traffic behavior for one or more hostnames.
Routing rules in the virtual service tell Red Hat OpenShift Service Mesh how to send the traffic for the virtual service to appropriate destinations.
Route destinations can be versions of the same service or entirely different services.

== Configuring virtual services with weighted load balancing

. Weighted load balancing requests are forwarded to instances in the pool according to a specific percentage.
+
In this example 80% to v1, 20% to v2.
+
To create a virtual service with this configuration, run the following command:
+
[source,sh,role=execute]
----
cat << EOF | oc apply -f -
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 80
    - destination:
        host: reviews
        subset: v2
      weight: 20
EOF
----
+
.Sample Output
[source,text,options=nowrap]
----
virtualservice.networking.istio.io/reviews created
----

. Refresh your browser tab containing the Bookinfo URL a few times and you'll see that occasionally you'll see the v2 of the book review app which has star ratings.
+
Accidentally close out of the tab?
No problem, run the following command to get the product page URL:
+
[source,sh,role=execute]
----
echo "http://$(oc -n istio-system get route istio-ingressgateway -o jsonpath='{.spec.host}')/productpage"
----
+
.Sample Output
[source,text,options=nowrap]
----
http://istio-ingressgateway-istio-system.apps.rosa-6n4s8.1c1c.p1.openshiftapps.com/productpage
----

== Summary 

Here you learned how to:

* Configure weighted load balancing using virtual services
